# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x = [1, 2, 3]
x + x

[1, 2, 3, 1, 2, 3]

In [21]:
x*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [11]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

<ipython-input-13-2f119c028196>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
# Also warning, but not an error instead infinity
1/arr

<ipython-input-14-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [24]:
call_length = np.array([120,128,190,137,240,325,19,340,287,169])
call_length/60

array([2.        , 2.13333333, 3.16666667, 2.28333333, 4.        ,
       5.41666667, 0.31666667, 5.66666667, 4.78333333, 2.81666667])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.

In [25]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [26]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [27]:
np.max(arr) #same as arr.max()

9

In [29]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [30]:
np.log10(arr)

<ipython-input-30-4473232fb1a0>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [31]:
np.log2(arr)

<ipython-input-31-45ec4562025d>:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [32]:
np.mean(arr)

4.5

In [33]:
np.var(arr)

8.25

In [34]:
np.median(arr)

4.5

In [35]:
np.std(arr)

2.8722813232690143

In [36]:
help(np.mean)

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For integer inputs,

In [37]:
x = np.random.randint(1,100,12).reshape(2,2,3)
x

array([[[77, 75, 60],
        [75, 41, 26]],

       [[67, 36,  6],
        [20, 83, 74]]])

In [38]:
np.std(x)

25.147343575194757

In [39]:
np.sqrt(x)

array([[[8.77496439, 8.66025404, 7.74596669],
        [8.66025404, 6.40312424, 5.09901951]],

       [[8.18535277, 6.        , 2.44948974],
        [4.47213595, 9.11043358, 8.60232527]]])